### ISSUE TITLE
Dynamic Allocation Implementation

### ISSUE THREAD

**Issue by nslowell** [FreeRTOS/Lab-Project-FreeRTOS-POSIX#1]
Could the posix implementation be used with only DYNAMIC allocation (STATIC allocation disabled)?  Is there something that prevents this?

**Comment by RichardBarry** [comment]
Not currently.  We aim to ensure libraries can be used in projects that do not permit dynamic allocation.  Whereas the kernel enables you turn turn static and dynamic allocation off individually, the posix library only uses static on the assumption that is suitable whether dynamic is permitted or not.
