### ISSUE TITLE
pthread_detach

### ISSUE THREAD

**Issue by JoaoVitorTeixeira** [FreeRTOS/Lab-Project-FreeRTOS-POSIX#10]
Hello!

Currently POSIX by FreeRTOS has the pthread_join function:
https://github.com/FreeRTOS/Lab-Project-FreeRTOS-POSIX/blob/0c6cec978cd8163c8640c7c157cccba457dedabc/include/FreeRTOS_POSIX/pthread.h#L362

But it does not have the pthread_detach function.
I wonder why the pthread_detach function was not implemented?
How can I implement this function using FreeRTOS?

**Comment by cobusve** [comment]
The FreeRTOS Posix implementation is in the Labs area because it is still incomplete. It would be much appreciated if you coould contribute an implementation. You can do so by creating a Pull Request to this repository so that we can include it for other users who need this functionality.

**Comment by JoaoVitorTeixeira** [comment]
Ok! I will create a Pull Request.

**Comment by JoaoVitorTeixeira** [comment]
@cobusve Hi! I created a  PR. Could you give me a feedback?

**Comment by ravibhagavandas** [comment]
Hi @JoaoVitorTeixeira,
Thanks for raising the PR.

We have added tests for the `pthread_detach` implementation in this [PR](https://github.com/aws/amazon-freertos/pull/3439) and have merged your pull request to this repo. 
I will close this issue.
