### ISSUE TITLE
Problems using pthread_create

### ISSUE THREAD

**Issue by dadodasilva94** [FreeRTOS/Lab-Project-FreeRTOS-POSIX#12]
I had some problems using pthread_create to create the fisrt task of the system.
The system only works when I use xTaskCreate to create just the first task.
Can someone help me?
Thank you!

**Comment by dan4thewin** [comment]
I'm sorry no one responded.  Given the age of this issue, I'll close it.  If you still need help, would you please open a new issue.  Thank you.
