### ISSUE TITLE
Not compling FREERTOS_POSIX_MUTEX_INITIALIZER 

### ISSUE THREAD

**Issue by snahmad** [FreeRTOS/Lab-Project-FreeRTOS-POSIX#18]
#define FREERTOS_POSIX_MUTEX_INITIALIZER \
    ( ( ( pthread_mutex_internal_t )         \
    {                                        \
        .xIsInitialized = pdFALSE,           \
        .xMutex = { { 0 } },                 \
        .xTaskOwner = NULL,                  \
        .xAttr = { .iType = 0 }              \
    }                                        \
        )                                    \
    )
FreeRTOS_POSIX_internal.h:64:5: error: incompatible types when initializing type 'long unsigned int' using type 'pthread_mutex_internal_t' {aka 'struct pthread_mutex_internal'}

**Comment by dachalco** [comment]
Hi @snahmad 

1. Is this `FREERTOS_POSIX_MUTEX_INITIALIZER` being used in the application code? 
2. Which FreeRTOS port and compiler are you using?



The only use case of `FREERTOS_POSIX_MUTEX_INITIALIZER` in the +POSIX code is at [FreeRTOS_POSIX_pthread_mutex.c#L126](https://github.com/FreeRTOS/Lab-Project-FreeRTOS-POSIX/blob/master/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread_mutex.c#L126), but it's correctly used for assigning to a `pthread_mutex_internal_t` type, hence why I wonder whether the macro has been used elsewhere in the app.

**Comment by ravibhagavandas** [comment]
As Dave pointed, is this error coming from a usage of the initializer in application code ? If so can you show how is it being used ?
`FREERTOS_POSIX_MUTEX_INITIALIZER` is supposed to be an internal macro and should not be used in application code (hence defined in `FreeRTOS_POSIX_internal.h`). The correct usage should be to use `PTHREAD_MUTEX_INITIALIZER` as shown in the test example below:

https://github.com/aws/amazon-freertos/blob/dcbe7a6553bca8a4ae3f5a93aaf737aa64214e88/libraries/freertos_plus/standard/freertos_plus_posix/test/iot_test_posix_pthread.c#L711

**Comment by ravibhagavandas** [comment]
I will close the issue due to inactivity. Please open an issue if you still have issues.
