### ISSUE TITLE
How to use with configSUPPORT_DYNAMIC_ALLOCATION = 0 ?

### ISSUE THREAD

**Issue by begriffs** [FreeRTOS/Lab-Project-FreeRTOS-POSIX#21]
Hi, [this comment](https://github.com/FreeRTOS/Lab-Project-FreeRTOS-POSIX/issues/1#issuecomment-586453405) says that FreeRTOS+Posix uses only static memory allocation. However, I didn't succeed in using the project with the following settings in FreeRTOSConfig.h:

```c
#define configSUPPORT_DYNAMIC_ALLOCATION 0
#define configSUPPORT_STATIC_ALLOCATION  1
```

The failure happened because `pthread_create` uses `pvPortMalloc` here: https://github.com/FreeRTOS/Lab-Project-FreeRTOS-POSIX/blob/3b33c3467d1345d332752aa9c155da9683183c49/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread.c#L295

Is there an alternative function to `pthread_create` I should use in projects without dynamic allocation support?

**Comment by dachalco** [comment]
Hi @begriffs

Currently there is no such logic in our +POSIX library that switches between only static or only dynamic memory use. I'm not sure there's a POSIX mechanism to specify that either. You must support dynamic allocation with this library as [xTaskCreate is called here](https://github.com/FreeRTOS/Lab-Project-FreeRTOS-POSIX/blob/master/FreeRTOS-Plus-POSIX/source/FreeRTOS_POSIX_pthread.c#L341), and this uses `pvPortMalloc`.

**Comment by n9wxu** [comment]
Sadly the original comment is incorrect.  FreeRTOS+Posix only supports dynamic memory.
