### ISSUE TITLE
Missing definition of struct tm

### ISSUE THREAD

**Issue by krshnarajd** [FreeRTOS/Lab-Project-FreeRTOS-POSIX#24]
I am trying to evaluate the freertos+posix implementation. My existing code uses 'struct tm' for time related logic. While using library, I am getting build error as the struct tm is not defined.  I am unable to see the definition in FreeRTOS_POSIX/time.h. However the copy in the  amazon-freertos repo has the definition. 

-- commit link
https://github.com/aws/amazon-freertos/commit/19de73d66057d80d262febe3232482e1d3e4726c

Whether this commit will be merged to this repo or I shall switch to the amazon-freertos posix repo ?

**Comment by krshnarajd** [comment]
Thanks. I can see that amazon freertos posix is deprecated. Whether this repo also deprecated and read only ? I would like to add some changes (For ex: struct tm).

**Comment by johnrhen** [comment]
This repo has not been formally deprecated, and we'll still review PRs made to it.

**Comment by alfred2g** [comment]
closing issue, please reopen if you have more questions.
