### ISSUE TITLE
Does not work with ESP-IDF 5.2

### ISSUE THREAD

**Issue by kdschlosser** [FreeRTOS/Lab-Project-FreeRTOS-POSIX#32]
It is bumping heads with all kinds of things in the IDF and even more if I use posix compatibility for lwip

**Comment by ActoryOu** [comment]
Hi @kdschlosser,
Thank you for reaching out to us. We appreciate your interest in our services.

If you don't mind, could you please provide some context as to why you're looking to use this specific library with ESP-IDF? I ask because, according to the [official Espressif documentation](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/system/pthread.html), ESP-IDF already provides POSIX APIs.

Thank you.

**Comment by kdschlosser** [comment]
The POSIX api's are only available when compiling under linux. it doesn't provide the API's when compiling for an ESP32, Nothing that is complete anyhow... 

In my use case I am wanting to use a library that is written to run on linux. It has a dependency on pthreads and sockets. The ESP-IDF uses lwip to handle the IP stack and socket connections and lwip has compat headers for linux which satisfy the linux socket dependency. the last part is pthread and what the IDF has included in terms of compatibility to linux is not complete enough to satisfy the dependency where this library does provide everything that is needed.

**Comment by ActoryOu** [comment]
There's a possibility we may not have accounted for all the pthread APIs in our current implementation for various reasons. To address this, we would greatly value your assistance in compiling a complete list of the pthread APIs you're working with or expecting to use.

Apart from that, if you or any other contributors have developed code related to this project, particularly implementations of pthread APIs, we would be delighted to review and potentially incorporate your work. Your expertise and unique perspectives can significantly enhance the quality and functionality of our project.

Thank you.

**Comment by kdschlosser** [comment]
The problem is not so much missing portions of the API as it is the bumping of heads with portions of the API that are supplied by the ESP-IDF. The issue is the ESP-IDF doesn't supply enough of the API and that is where this library helps to fill in the blanks. Not to throw another twist into it the xtensa gcc compiler also provides a subset of glibc and that is causing some problems as well. I was able to sort out most of the issues by creating macros for missing types and things of that nature. After spending several days of hair pulling it finally compiled. whether or not it will actually run is a whole other animal and I have not gotten into yet as I still need to write the code to stitch everything together. It is a complex combination of the LVGL graphics framework, MicroPython and libvncserver running on an ESP32 MCU. Not an easy task to get the various pieces to not throw sand at each other while playing in the sand box, if you get my meaning. 

The ultimate goal of what I am doing is to create a way for users to build devices and write software for small devices with attached displays. The VNC (RFB Protocol) portion is to be able to develop and run the software on the MCU without having a display attached. More times than I can count I have developed something for a display only to end up changing the design because the display was to large or to small. This is a good way for a user to start developing without needing to have the initial investment of buying display hardware. It also provides a mechanism for providing support for production devices. Lots of companies are using MCU's to automate all kinds of things and support persons being able to connect to the device and see exactly what the user is seeing would be a fantastic feature to have available.

**Comment by ActoryOu** [comment]
Thank you for your detailed response. We appreciate the context you've provided. However, to better assist you, we'd need a more specific list of the components or features from this repository that you're trying to implement. Could you kindly outline these for us? This would help us provide more targeted support.

Thank you for your cooperation.
